# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - usersapinestjs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://github.com//
        username: ${{ secrets.AzureAppService_ContainerUsername_e006d1fe26274e46845ed21ece6e88ae }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5d062aac54dc4dfa890c89c5fab079cd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: github.com//${{ secrets.AzureAppService_ContainerUsername_e006d1fe26274e46845ed21ece6e88ae }}/users_nestjapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'usersapinestjs'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6099514d5f3447e99863ee6b241dc942 }}
        images: 'github.com//${{ secrets.AzureAppService_ContainerUsername_e006d1fe26274e46845ed21ece6e88ae }}/users_nestjapp:${{ github.sha }}'